global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'patcode-local'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'patcode'
    static_configs:
      - targets: ['patcode:8000']
    metrics_path: '/metrics'
  
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
